webapplication/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='moviapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movies/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

webapplication/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

webapplication/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=222)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

webapplication/movieproject/movieapp/forms.py
from django import forms
from . models import movies

class movieforms(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','des','year','img']

webapplication/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movies
from . forms import movieforms
# Create your views here.
def index(result):
    abc=movies.objects.all()
    content={'movie_list':abc}
    return render(result,'index.html',content)
def detail(value,movie_id):
    movie=movies.objects.get(id=movie_id)
    return render(value,'detail.html',{'abc':movie})
 #   return HttpResponse("this the movie number %s " % movie_id)

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get("name",)
        des = request.POST.get("des",)
        year = request.POST.get("year",)
        img = request.FILES["img"]
        movie=movies(name=name,des=des,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=movies.objects.get(id=id)
    form=movieforms(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html', {'form':form, 'abc':movie})

def delete(request,id):
    if request.method=='POST':
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

webapplication/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<input type="text" name="name" placeholder="enter the movie name">
<input type="text" name="des" placeholder="enter the movie desc">
<input type="text" name="year" placeholder="enter the movie year">
<input type="file" name="img">
<input type="submit">
</form>
{% endblock %}

webapplication/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>THE MOVE WORLD</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie details
      <div style="text-align:center;background-color:red">
    <a href="{% url 'moviapp:add_movie' %}" class="btn btn-outline">Click Here To Add Movies</a>
</div>
  </a>
</nav>
{% block body %}
{% endblock %}
 </body>
</html>

webapplication/movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  do  you want to delete the file?
  <input type="submit">

</form>

webapplication/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Details</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{abc.img.url}}" width="300" height="300">
        </div>
    <div class="col-md-6">
        <h5>{{abc.name}}</h5>
        {{abc.des}}<br>
        The Year Of Movie : {{abc.year}}<br>
        <a class="btn btn-warning" href="{% url 'moviapp:update' abc.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'moviapp:delete' abc.id %}">delete</a>
    </div>


    </div>
</div>
</body>
</html>
{% endblock %}

webapplication/movieproject/templates/edit.html
<form  method="POST" enctype="multipart/form-data">
   {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

webapplication/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row">
{% for i in movie_list %}
<div class="col-md-4">
<div class="card" style="width: 16rem;height:30rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt=" " width="800" height="200">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p style="height:150px;" class="card-text">{{i.des}}</p>
    <a href="{% url 'moviapp:detail' i.id %}" class="btn btn-primary">Check  The Details</a>

  </div>
</div>
</div>
    {% endfor %}

</div>
</div>

{% endblock %}